<?php
// подключение плагина DataTables
$this->dataTables();
?>

<h3><?= $this->translate('Действия над заказами') ?></h3>

	<form class="form-std" id="filterForm" method="post" action="/shop/orders-log/filter">
	<b><?= $this->translate('Фильтр') ?></b>
	<div class="data-filter">
		<table>
			<tr valign="top">
				<td>
					<?= $this->translate('Менеджеры') ?>:
					<div class="pdd-5-0">
					<?= $this->formSelect('fManager', $this->fManager, array('class' => 'smooth'), $this->managerOptions) ?>
					</div>
				</td>
			</tr>
		</table>
	</div>
	</form>

<table id="tDataTable" class="display" width="100%">
<thead>
	<tr>
		<th><?= $this->translate('ID') ?></th>
		<th><?= $this->translate('Заказ') ?></th>
		<th><?= $this->translate('Менеджер/Телефон') ?></th>
		<th><?= $this->translate('Сайт заказа') ?></th>
		<th><?= $this->translate('Действие') ?></th>
		<th><?= $this->translate('Дата') ?></th>
	</tr>
</thead>
</table>