<h1><?= $this->translate('История заказов') ?></h1>	

<div class="box">
	<div class="inner">
		<p><a href="<?= $this->url(array(), 'shop::userOrders') ?>">&larr; <?= $this->translate('назад к списку заказов') ?></a></p>
		<?php if (!empty($this->order)): ?>
		
			<h3><?= $this->translate('Номер заказа') ?>: <?= $this->order->number ?></h3>
			<p><?= $this->showDate($this->order->created) ?></p>
			<p><b><?= $this->translate('Список товаров')?>:</b></p>
			<table class="light" width="100%">
				<tr>
					<th><?= $this->translate('Код') ?></th>
					<th><?= $this->translate('Название') ?></th>
					<th><?= $this->translate('Артикул') ?></th>
					<th><?= $this->translate('Цена') ?></th>
					<th><?= $this->translate('Кол-во') ?></th>
					<th><?= $this->translate('Сумма') ?></th>
				</tr>
				<?php $total = 0; ?>
				<?php foreach ((array) $this->posList as $pos): ?>
					<tr>
						<td><?= $pos->code ?></td>
						<td><?= $pos->name ?></td>
						<td><?= $pos->articul ?></td>
						<td align="right" nowrap="nowrap"><?= Lv7_Service_Text::asPrice($pos->price, 2) ?> р.</td>
						<td align="center"><?= $pos->quantity ?></td>
						<td align="right" nowrap="nowrap"><?= Lv7_Service_Text::asPrice($pos->price * $pos->quantity, 2) ?> р.</td>
					</tr>
					<?php $total += $pos->quantity; ?>
				<?php endforeach; ?>
				<tr style="font-weight:bold;">
					<td colspan="4"><?= $this->translate('Товары') ?></td>
					<td align="center"><?= $total ?></td>
					<td align="right" nowrap="nowrap"><?= Lv7_Service_Text::asPrice($this->order->params->goodsCost, 2) ?> р.</td>
				</tr>
				<tr>
					<td colspan="5"><?= $this->translate('Доставка') ?></td>
					<td align="right" nowrap="nowrap"><?= Lv7_Service_Text::asPrice($this->order->params->deliveryCost, 2) ?> р.</td>
				</tr>
				<tr style="font-weight:bold; font-size:1.2em;">
					<td colspan="5"><?= $this->translate('Итого') ?></td>
					<td align="right" nowrap="nowrap"><?= Lv7_Service_Text::asPrice($this->order->params->totalCost, 2) ?> р.</td>
				</tr>
			</table>
			<br><br>
			<p><b><?= $this->translate('Контактная информация') ?>:</b></p>
			<div class="shop-user-order-info">
			<p>
				<small><?= $this->translate('Контактное лицо') ?>:</small> 
				<big><?= $this->order->params->contactFace ?></big>
				</p>
			<p>
				<small><?= $this->translate('Телефон') ?>:</small> 
				<big><?= $this->order->params->phone ?></big>
				</p>
			<p>
				<small><?= $this->translate('E-mail') ?>:</small> 
				<big><?= $this->order->params->email ?></big>
				</p>
			<p>
				<small><?= $this->translate('Адрес') ?>:</small> 
				<big><?= $this->order->params->address ?></big>
				</p>
			<p>
				<small><?= $this->translate('Способ доставки') ?>:</small> 
				<big ><?= $this->order->params->deliveryName ?></big>
				</p>
			<p>
				<small><?= $this->translate('Способ оплаты') ?>:</small> 
				<big><?= $this->order->params->paymentMethodName ?></big>
				</p>
			<p>
				<small><?= $this->translate('Дисконтная карта') ?>:</small> 
				<big><?= $this->order->params->discountCard ?></big>
				</p>
			<p>
				<small><?= $this->translate('Дополнительные пожелания') ?>:</small> 
				<big><?= $this->order->params->comments ?></big>
				</p>
			</div>
		<?php endif; ?>
	</div>
	<div class="clear"></div>
	<div class="top_bg"></div>
	<div class="bot_bg"></div>
</div>
