<?php 
$this->fancybox(true, false);
?>
<div class="box unit-page">
	<div class="inner">
		<h1><?= $this->translate('Корзина') ?></h1>	
		<div id="shop-basket-items-table">
		<?php 
		include 'index.ajax.phtml';
		?>
		</div>
		<div style="height:100px">
			<div id="shop-basket-items-table-confirm">
				<div><?= $this->translate('Изменения сохранены!') ?></div>
			</div>
		</div>
	</div>
	<div class="clear"></div>
	<div class="top_bg"></div>
	<div class="bot_bg"></div>
</div>