<?php if ($_GET['process'] == 'point'){ ?>

    <?php $points = $this->clientPoints; ?>
    <script type="text/javascript">
        function init () {
            /**
             * Создаем мультимаршрут.
             * Первым аргументом передаем модель либо объект описания модели.
             * Вторым аргументом передаем опции отображения мультимаршрута.
             * @see https://api.yandex.ru/maps/doc/jsapi/2.1/ref/reference/multiRouter.MultiRoute.xml
             * @see https://api.yandex.ru/maps/doc/jsapi/2.1/ref/reference/multiRouter.MultiRouteModel.xml
             */
            var multiRoute = new ymaps.multiRouter.MultiRoute({
                // Описание опорных точек мультимаршрута.
                referencePoints: [
                    [55.905353, 37.611104],
                    [<?php echo $points['clientPointB']; ?>, <?php echo $points['clientPointA']; ?>]
                ],
                // Параметры маршрутизации.
                params: {
                    // Ограничение на максимальное количество маршрутов, возвращаемое маршрутизатором.
                    results: 2
                }
            }, {
                // Автоматически устанавливать границы карты так, чтобы маршрут был виден целиком.
                boundsAutoApply: true
            });

            // Создаем кнопки для управления мультимаршрутом.
            var trafficButton = new ymaps.control.Button({

                }),
                viaPointButton = new ymaps.control.Button({

                });

            // Объявляем обработчики для кнопок.
            trafficButton.events.add('select', function () {
                /**
                 * Задаем параметры маршрутизации для модели мультимаршрута.
                 * @see https://api.yandex.ru/maps/doc/jsapi/2.1/ref/reference/multiRouter.MultiRouteModel.xml#setParams
                 */
                multiRoute.model.setParams({ avoidTrafficJams: true }, true);
            });

            trafficButton.events.add('deselect', function () {
                multiRoute.model.setParams({ avoidTrafficJams: false }, true);
            });

            viaPointButton.events.add('select', function () {
                var referencePoints = multiRoute.model.getReferencePoints();
                referencePoints.splice(1, 0, "Москва, ул. Солянка, 7");
                /**
                 * Добавляем транзитную точку в модель мультимаршрута.
                 * Обратите внимание, что транзитные точки могут находится только
                 * между двумя путевыми точками, т.е. не могут быть крайними точками маршрута.
                 * @see https://api.yandex.ru/maps/doc/jsapi/2.1/ref/reference/multiRouter.MultiRouteModel.xml#setReferencePoints
                 */
                multiRoute.model.setReferencePoints(referencePoints, [1]);
            });

            viaPointButton.events.add('deselect', function () {
                var referencePoints = multiRoute.model.getReferencePoints();
                referencePoints.splice(1, 1);
                multiRoute.model.setReferencePoints(referencePoints, []);
            });

            // Создаем карту с добавленными на нее кнопками.
            var myMap = new ymaps.Map('map', {
                center: [55.750625, 37.626],
                zoom: 7,
                controls: [trafficButton, viaPointButton]
            }, {
                buttonMaxWidth: 300
            });

            // Добавляем мультимаршрут на карту.
            myMap.geoObjects.add(multiRoute);
        }

        ymaps.ready(init);


    </script>
    <div id="map"></div>
    <?php
    // выводим скрытно в hidden координаты пользователя
    echo $this->clientPointA;
    echo $this->clientPointB;
    echo $this->YandexDeliveryAddressAPI;
    ?>
<?php } elseif($_GET['process'] == 'intervals') { // Кирилл yandexDelivery: вставил селектор офферов цен для express ?>
    <?php if ($this->kmError == 1){ ?>
        <i class="YandexDeliveryError">Расстояние превышает 80 км.</i></br>
    <?php } ?>
    <?php if ($this->errorLimit == 1){ ?>
        <i class="YandexDeliveryError">Большие габариты груза</i>
    <?php } ?>
    <?php if ($this->errorIntervals == 1){ ?>
        <i class="YandexDeliveryError">Свободных машин нет</i>
    <?php } ?>
    <ul class="offersExpress" style="display: none;">
        <?php
        $i = 0;
        while ($i < count($this->intervals)-2){
            $i++;
            ?>
            <li id="id-<?php echo $i; ?>" data-id="<?php echo $this->intervals[$i]['payload']; ?>"><?php echo $this->intervals[$i]['price']; ?></li>
            <?php
        }
        ?>
    </ul>
    <?php echo $this->YandexDeliveryIntervals; ?>
<?php } ?>