<?php if ($this->posList): ?>

	<table border="1" cellpadding="3" cellspacing="0">
		<thead>
			<tr>
				<th>Бренд</th>
				<th>Номер</th>
				<th>Название товара</th>
				<th>Цена</th>
				<th>Количество</th>
				<th>Сумма</th>
			</tr>
		</thead>
		<tbody>
		<?php 
		$quantity = 0;
		$sum = 0;
		?>
		<?php foreach ($this->posList as $pos): ?>
			<tr>
				<td><?= $pos->man_brand ?></td>
				<td><?= $pos->man_number ?></td>
				<td><?= $pos->name ?></td>
				<td align="right"><?= Lv7_Service_Text::asPrice($pos->price) ?> руб.</td>
				<td align="center"><?= $pos->quantity ?></td>
				<td align="right"><?= Lv7_Service_Text::asPrice($pos->price * $pos->quantity) ?> руб.</td>
			</tr>
			<?php 
			$quantity += $pos->quantity;
			$sum += $pos->price * $pos->quantity;
			?>
		<?php endforeach; ?>
		</tbody>
		<tfoot>
			<tr>
				<th colspan="4" align="left">Итого</th>
				<th align="center"><?= $quantity ?></th>
				<th align="right"><?= Lv7_Service_Text::asPrice($sum) ?> руб.</th>
			</tr>
		</tfoot>
	</table>

<?php endif; ?>
